title: Yasir Ibrahim
description: A Phd Candidate
author: Yasir Ibrahim
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grgor08.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-hamilton
avatar: /DSC01405.jpg
email: y.omeribrahim@hotmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: DSC01405.jpg
social:
  linkedin: "https://www.linkedin.com/in/yasir-abdelaziz/"
  scholar: "https://scholar.google.com/citations?user=1X2D49kAAAAJ&hl=en&authuser=1"
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
