# Site settings
title: Yasir Ibrahim
description: "Graduate Research Assistant at Texas A&M University"
baseurl: ""
url: "https://grgor08.github.io"
profilepic: '/images/DSC01405.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: "Yasir Ibrahim"
  email: "y.omeribrahim@hotmail.com"
  linkedin: "https://www.linkedin.com/in/yasir-abdelaziz/"
  scholar: "https://scholar.google.com/citations?user=1X2D49kAAAAJ&hl=en&authuser=1"

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
